different-server:
  enabled: false
  server-ip: "event-server"

hub-server: "hub"

voting-duration: 60

regen:
  enabled: true
  backup-folder: "regen"

worlds:
  - world_minecraft_plains
  - world_minecraft_desert
  - world_minecraft_snowy_fields
  - world_minecraft_cherry
  - world_minecraft_badlands
  - world_minecraft_mushroom

world-options:
  - "world_minecraft_plains"
  - "world_minecraft_desert"
  - "world_minecraft_snowy_fields"
  - "world_minecraft_cherry"
  - "world_minecraft_badlands"
  - "world_minecraft_mushroom"

allowed-commands-before:
  - "msg"
  - "tpa"
  - "tpahere"
  - "tpaccept"
  - "tpcancel"

allowed-commands-during:
  - "msg"
